return {
  {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
      icons = {
        mappings = vim.g.have_nerd_font,
        rules = {
          { pattern = 'elete', icon = '󰗨', color = 'red' },
          { pattern = 'hange', icon = '~', color = 'yellow' },
          { pattern = 'ulticursor', icon = '󰇀', color = 'yellow' },
          { pattern = 'aste', icon = '', color = 'cyan' },
        },
        keys = vim.g.have_nerd_font and {} or {
          Up = '<Up> ',
          Down = '<Down> ',
          Left = '<Left> ',
          Right = '<Right> ',
          C = '<C-…> ',
          M = '<M-…> ',
          D = '<D-…> ',
          S = '<S-…> ',
          CR = '<CR> ',
          Esc = '<Esc> ',
          ScrollWheelDown = '<ScrollWheelDown> ',
          ScrollWheelUp = '<ScrollWheelUp> ',
          NL = '<NL> ',
          BS = '<BS> ',
          Space = '<Space> ',
          Tab = '<Tab> ',
          F1 = '<F1>',
          F2 = '<F2>',
          F3 = '<F3>',
          F4 = '<F4>',
          F5 = '<F5>',
          F6 = '<F6>',
          F7 = '<F7>',
          F8 = '<F8>',
          F9 = '<F9>',
          F10 = '<F10>',
          F11 = '<F11>',
          F12 = '<F12>',
        },
      },

      spec = {
        { '<leader>e', group = '[E]xecute', mode = 'v', icon = { icon = '', color = 'azure' } },
        { '<leader>r', group = '[R]eplace', mode = 'v', icon = { icon = '󰛔', color = 'azure' } },
        { '<leader>t', group = '[T]oggle', mode = 'v', icon = { icon = '', color = 'azure' } },
        { '<leader>e', group = '[E]xecute', icon = { icon = '', color = 'azure' } },
        { '<leader>b', group = '[B]uffer', icon = { icon = '󰈔', color = 'azure' } },
        { '<leader>r', group = '[R]eplace', icon = { icon = '󰛔', color = 'azure' } },
        { '<leader>s', group = '[S]earch', icon = { icon = '', color = 'azure' } },
        { '<leader>w', group = '[W]orkspace', icon = { icon = '󰈔', color = 'azure' } },
        { '<leader>o', group = '[O]pen', icon = { icon = '', color = 'azure' } },
        { '<leader>n', group = '[N]ew', icon = { icon = '', color = 'azure' } },
        { '<leader>k', group = '[K][M][S]', icon = { icon = '󱚝', color = 'orange' } },
        { '<leader>km', group = '[K][M][S]', icon = { icon = '󱚝', color = 'orange' } },
        { '<leader>t', group = '[T]oggle', icon = { icon = '', color = 'azure' } },
      },
    },
  },
}
